name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a53c1abf9f68287ea584721237142fa7544668f7da9d9ebe8fca416a228db1c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
