name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2739cf64a14de702fdcfd10df928a162000745b3922d51bf7a021ff11cfff563"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19.2", "1.19"]
