name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf5f7e38cfa34248ea6bd58c85543b6bbbcb62e1317b5262e7290cd549013877"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
